name: "postprocess"
backend: "python"

max_batch_size: 

input [
  {
    name:
    data_type: 
    dims: 
  },
]

output [
  {
    name: 
    data_type: 
    dims: 
  }
]

instance_group [
  {
    kind: 
    count: 
    gpus: 
  }
]